# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jE5puhvj12nroSPq5AoaZQjVa0PL1ElD
"""

num1 = float(input("Birinchi raqamni kiriting: "))
num2 = float(input("Ikkinchi raqamni kiriting: "))
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Xatolik! Nolga bo'lish mumkin emas."
    return x / y

print("Operatsiyani tanlang:")
print("1. Qo'shish (+)")
print("2. Ayirish (-)")
print("3. Ko'paytirish (*)")
print("4. Bo'lish (/)")

operation = input("Tanlangan operatsiya: ")

if operation == '1':
    print(f"{num1} + {num2} = {add(num1, num2)}")
elif operation == '2':
    print(f"{num1} - {num2} = {subtract(num1, num2)}")
elif operation == '3':
    print(f"{num1} * {num2} = {multiply(num1, num2)}")
elif operation == '4':
    print(f"{num1} / {num2} = {divide(num1, num2)}")
else:
    print("Noto'g'ri tanlov!")